### ISSUE TITLE
http://minigun.io/ 404s

### ISSUE THREAD

**Issue by DannyCork** [shoreditch-ops/minigun#18]
https://artillery.io/minigun/ contains 4 404s
Each of these links generate a 404

4. Learn more
There's plenty you can do in your scripts:

Specify multiple load-phases
Set custom headers
Use payload files for POST data
Set expectations on response latency

I didn't see the source for https://artillery.io/minigun/  on github so I can't fix the problem :(

**Comment by hassy** [comment]
Cheers @DannyCork - Minigun has a new website now at http://minigun.io/ (source is at https://github.com/shoreditch-ops/minigun-www) and the old one will be retired.
