### ISSUE TITLE
Feature request: Addition of Phase information in report

### ISSUE THREAD

**Issue by tomgco** [shoreditch-ops/minigun#34]
This would be nice as it would be possible to implement annotations on graphs, to show when the tests ramp up / down.

![newplot](https://cloud.githubusercontent.com/assets/524382/12174351/f57ee25e-b553-11e5-9e28-26c20e1b1595.png)

The phases in this graph are:

```json
    "phases": [
      { "duration": 120, "arrivalRate": 1, "name": "Search ramp-up" },
      { "duration": 60, "arrivalRate": 5, "name": "Search ramp-up" }
    ],
```

**Comment by hassy** [comment]
:+1: the name of the phase should be included somewhere - along the X axis perhaps. Not sure if the charting library Minigun is using supports that though.

**Comment by tomgco** [comment]
I believe that in the graphing library that minigun uses, support for annotations are included:
http://metricsgraphicsjs.org/examples.htm#annotations

Something like that could be really helpful when looking at the graphs.
