### ISSUE TITLE
Investigate using Wreck instead of Request

### ISSUE THREAD

**Issue by StevenWeathers** [shoreditch-ops/minigun#6]
Especially considering this applications goal is to load test something I would recommend against using Request module, its bloated and less performant than something like Wreck

**Comment by hassy** [comment]
@StevenWeathers Thanks for your suggestion. I haven't used Wreck myself and Request has been performant-enough for now. Wreck does not seem to be as featureful as Request either. I'd be interested in a performance comparison between the two. Is worse performance something you ran into with Request?

**Comment by StevenWeathers** [comment]
While I agree Wreck isn't as featureful as request, that's one of the big reasons its a better use as its less bloated and requires far less dependencies.  Overall I've seen better performance using Wreck than Request but haven't formally put together any benchmarks.  I'll try to find time to do so in the near future and share them with you.

**Comment by hassy** [comment]
I'm working on a suite of benchmarks comparing Request and Wreck - so far I'm seeing that Request is ~20% slower - I'll update this when I have the final results.

**Comment by hassy** [comment]
Closing - MG will continue to use Request by default as Wreck is too limited. A custom Wreck-based engine would be easy to implement if someone really wanted one.
