### ISSUE TITLE
Socket.io usage example

### ISSUE THREAD

**Issue by KlonD90** [shoreditch-ops/minigun#9]
It's great library but i need some examples with Socket.io. Can you help me with this?

**Comment by hassy** [comment]
@KlonD90 I'm not really familiar with Socket.io but if it's possible to connect directly to the WebSocket endpoint of a Socket.io server, then you will be able to use the "ws" engine in Minigun - small example [here](https://github.com/artilleryio/minigun-core/blob/master/test/scripts/hello_ws.json).

It's probably worth investigating adding full Socket.io support to Minigun as it's a very popular library; it shouldn't be too much work.
